# fly.toml app configuration file generated for casca on 2023-05-02T13:49:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "casca"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
